title: Alex Sulimanov
description: > # this means to ignore newlines until "baseurl:"
  Alex Sulimanov"
permalink: ':title/'
baseurl: ""
url: "https://sulimanov.github.io"
site-twitter: "https://twitter.com/alex_sulimanov"

# Author Settings
author: Alex Sulimanov
author-img: avatar.jpg
about-author: San Francisco-based entrepreneur, ML/AI engineering leader & adventurer.
social-twitter: alex_sulimanov
social-facebook: asulimanov
social-github: sulimanov
social-linkedin: sulimanov
social-email: alex@sulimanov.com

# Disqus
discus-identifier: alexsulimanov

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]